### ISSUE TITLE
Add CI for PRs

### ISSUE THREAD

**Issue by woodruffw** [Homebrew/ruby-macho#13]
Title says it all.

**Comment by woodruffw** [comment]
https://travis-ci.org/Homebrew/ruby-macho/builds

**Comment by UniqMartin** [comment]
Cool! :sunglasses: Any reason why you went with Ruby 1.9.3 for testing? My question is somewhat motivated by Homebrew's use of this code. Most users run on Ruby 2.0.0, but we also test with Ruby 1.8.7 because we still don't want to leave those legacy users completely out in the cold. For this project to become a full replacement for Homebrew's current Mach-O handling this code would need to stay compatible with Ruby 1.8.7 (even if it is somewhat annoying to work with some of the restrictions Ruby 1.8.7 imposes).

**Comment by woodruffw** [comment]
> Any reason why you went with Ruby 1.9.3 for testing?

Nope, no particular reason besides that being what I tested with on the other CI service I was using.

I'll add 2.0.0 and 1.8.7 to the matrix, but I suspect that 1.8.7 builds will probably fail until I get rid of all the 1.9 features I use (`require_relative`, `&:`, etc).

I'm going to create a branch for 1.8.7 compatibility changes today.

**Comment by UniqMartin** [comment]
> I'll add 2.0.0 and 1.8.7 to the matrix, but I suspect that 1.8.7 builds will probably fail until I get rid of all the 1.9 features I use (`require_relative`, `&:`, etc).

Thanks! I'm partially guilty of those failures because I suggested `flat_map` but am now realizing it doesn't exist in Ruby 1.8.7 and only works for Homebrew because of [`extend/enumerable.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/extend/enumerable.rb). Sorry about that!

**Comment by woodruffw** [comment]
> I suggested flat_map but am now realizing it doesn't exist in Ruby 1.8.7 and only works for Homebrew because of extend/enumerable.rb. Sorry about that!

No worries! If backwards availability of methods becomes a pain, we should probably make our own little *extend* implementations.
